# Generated by Django 4.0.4 on 2022-06-01 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=135)),
                ('description', models.CharField(default=False, max_length=135)),
                ('type', models.CharField(choices=[('back-end', 'Back End'), ('front-end', 'Front End'),
                                                   ('ios', 'Ios'), ('android', 'Android')], max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors',
                                             to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=135)),
                ('desc', models.CharField(max_length=135)),
                ('tag', models.CharField(choices=[('bug', 'Bug'), ('amelioration', 'Improvement'), ('taches', 'Task')],
                                         max_length=20)),
                ('priority', models.CharField(choices=[('faible', 'Weak'), ('moyenne', 'Average'), ('eleve', 'High')],
                                              max_length=20)),
                ('status', models.CharField(choices=[('a faire', 'To Do'), ('en cours', 'In Progress'),
                                                     ('termine', 'Finished')], max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               related_name='issues_assignee', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='issues', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='issues', to='project.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('AUTHOR', 'All'), ('CONTRIBUTOR', 'Read')], max_length=30)),
                ('role', models.CharField(choices=[('auteur', 'Author'), ('contributeur', 'Contributor')],
                                          max_length=135)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors',
                                              to='project.projects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors',
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=135)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                             to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                            to='project.issues')),
            ],
        ),
    ]
